# ==============================
# PROFILE
# ==============================
spring.profiles.active=social

# ==============================
# SERVER
# ==============================
server.port=${PORT:8080}

# ==============================
# DATABASE
# --==============================
spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==============================
# JPA
# ==============================
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ==============================
# JWT
# ==============================
jwt.secret=${JWT_SECRET}

# ==============================
# BREVO
# ==============================
BREVO_API_KEY=${BREVO_API_KEY}

# ==============================
# GOOGLE GEMINI AI
# ==============================
GROQ_API_KEY=${GROQ_API_Key}

# ==============================
# ADVANCED CONFIG
# ==============================
spring.main.allow-circular-references=true