# ==============================
# PROFILE
# ==============================
spring.profiles.active=social

# ==============================
# SERVER
# ==============================
server.port=${PORT:8080}

# ==============================
# DATABASE
# ==============================
spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==============================
# JPA
# ==============================
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ==============================
# JWT
# ==============================
jwt.secret=${JWT_SECRET}

# ==============================
# BREVO
# ==============================
BREVO_API_KEY=${BREVO_API_KEY}

# ==============================
#
# Spring AI Google Gemini Configuration
spring.ai.google.genai.api-key=${gcp_id}
spring.ai.google.genai.chat.options.model=gemini-2.0-flash

# ==============================
# ADVANCED CONFIG
# ==============================
spring.main.allow-circular-references=true